/*
 * Filename: e:\newblog\my2022\aiyou-blog-s\.github\workflows\verify.yml
 * Path: e:\newblog\my2022\aiyou-blog-s
 * Created Date: Saturday, February 19th 2022, 8:19:56 pm
 * Author: aiyoudiao
 * 
 * Copyright (c) 2022 aiyoudiao
 */

# This is a basic workflow to help you get started with Actions

name: verify

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.X"
      - name: install dep
        run: npm install
      - name: build app
        run: npm run build